all: solve

run: all sample input
	./solve sample
	@echo "----------------------------------"
	./solve input

format:
	clang-format -i *.cpp

%.o: %.cpp
	$(CXX) $(CPPFLAGS) -c -o $@ $^

solve: solve.o
	$(CXX) $(CPPFLAGS) -o $@ $<

clean:
	-rm *.o solve

